JOIN_CMD=kubeadm\ join\ 10.4.94.93:6443\ --token\ t5jze0.zgzvqz7iy13fjj3x\ --discovery-token-ca-cert-hash\ sha256:9382f4b5f3410281fff4e2d88f77a4b8cec2436773da4c19c888ad91c86eaa07\ 
#!/usr/bin/env bash
# =============================================================================
# scripts/worker.sh — Run on each worker node
#
# Injected variable (set by setup.sh wrapper):
#   JOIN_CMD  Full "kubeadm join ..." command string
# =============================================================================

set -euo pipefail

echo "[worker] === Joining cluster ==="

# Idempotent: skip if already joined
if [ -f /etc/kubernetes/kubelet.conf ]; then
  echo "[worker] Already joined — skipping kubeadm join"
else
  # Run the kubeadm join command generated by the control-plane
  # shellcheck disable=SC2086
  eval sudo ${JOIN_CMD}
fi

echo "[worker] === Successfully joined the cluster ==="
