#!/usr/bin/env bash
# =============================================================================
# scripts/worker.sh — Run on each worker node
#
# Injected variable (set by setup.sh wrapper):
#   JOIN_CMD  Full "kubeadm join ..." command string
# =============================================================================

set -euo pipefail

echo "[worker] === Joining cluster ==="

# Run the kubeadm join command generated by the control-plane
# shellcheck disable=SC2086
eval sudo ${JOIN_CMD}

echo "[worker] === Successfully joined the cluster ==="
